import Link from "next/link";
import { Breadcrumbs, LandingSection, PageHero } from "./LandingPageElements";

const pages = {
  about: { title: "درباره ما", description: "تخصص، تجربه و تعهد برای پایداری برق زیرساخت‌های حساس", image: "/images/about.webp", intro: "کلینیک یو پی اس مجموعه‌ای تخصصی در زمینه مشاوره، تأمین، نصب، راه‌اندازی و نگهداری سامانه‌های برق اضطراری است. ما با تکیه بر تجربه اجرایی و شناخت دقیق تجهیزات، راهکاری متناسب با نیاز واقعی هر مجموعه ارائه می‌کنیم.", sections: [{ title: "مأموریت ما", text: "کاهش ریسک توقف کسب‌وکارها و مراکز حیاتی با طراحی و اجرای راهکارهای قابل اتکا برای تأمین و حفاظت انرژی الکتریکی." }, { title: "چشم‌انداز", text: "تبدیل‌شدن به مرجع قابل اعتماد خدمات یو پی اس، باتری، استابیلایزر و ژنراتور با پشتیبانی سریع و شفاف." }, { title: "چرا کلینیک یو پی اس؟", text: "مشاوره فنی بی‌طرفانه، انتخاب تجهیزات معتبر، اجرای استاندارد، مستندسازی و خدمات پس از فروش پاسخ‌گو." }] },
  services: { title: "خدمات", description: "راهکار کامل از طراحی تا نگهداری زیرساخت برق اضطراری", image: "/images/static/airplane_blackout.webp", intro: "خدمات کلینیک یو پی اس تمام چرخه عمر تجهیزات را پوشش می‌دهد؛ از بازدید و محاسبه ظرفیت تا نصب، مانیتورینگ، سرویس دوره‌ای و تعمیرات تخصصی.", cards: [{ title: "فروش و تأمین تجهیزات", text: "تأمین یو پی اس، باتری، استابیلایزر، موتور برق و دیزل ژنراتور متناسب با بار مصرفی.", href: "/services/sales" }, { title: "تعمیرات تخصصی", text: "عیب‌یابی، تعمیر برد و پاور، تعویض قطعات و تست عملکرد تجهیزات.", href: "/services/repair" }, { title: "خدمات پس از فروش", text: "قرارداد نگهداری، بازدید دوره‌ای، تست باتری و پشتیبانی اضطراری.", href: "/services/after-sales" }] },
  "after-sales": { title: "خدمات پس از فروش", description: "نگهداری پیشگیرانه برای کاهش توقف‌های ناخواسته", image: "/images/static/24hour_atm.webp", intro: "پایداری سامانه برق اضطراری به نگهداری منظم وابسته است. برنامه خدمات پس از فروش ما بر اساس نوع تجهیز، شرایط محیطی و حساسیت بار تدوین می‌شود.", sections: [{ title: "قراردادهای سرویس و نگهداری", text: "بازدید دوره‌ای، ثبت پارامترها، پاک‌سازی، تست بار، کنترل اتصالات و ارائه گزارش فنی." }, { title: "پایش سلامت باتری", text: "اندازه‌گیری ولتاژ و مقاومت داخلی، شناسایی سلول‌های ضعیف و برنامه‌ریزی تعویض پیش از خرابی." }, { title: "پشتیبانی اضطراری", text: "هماهنگی سریع تیم فنی برای عیب‌یابی و بازگرداندن سامانه به وضعیت پایدار." }] },
  repair: { title: "تعمیرات یو پی اس", description: "عیب‌یابی اصولی و بازگردانی مطمئن تجهیزات به مدار", image: "/images/static/repairing_electricity.webp", intro: "فرآیند تعمیر با بررسی شرایط خطا و تست کامل ورودی، خروجی، شارژر، اینورتر و بانک باتری آغاز می‌شود. پس از تأیید هزینه، تعمیر و تست نهایی تحت بار انجام خواهد شد.", sections: [{ title: "پذیرش و عیب‌یابی", text: "ثبت مشخصات دستگاه و خطاها، بررسی ظاهری و انجام آزمون‌های الکتریکی." }, { title: "تعمیر و تأمین قطعه", text: "تعمیر بردهای کنترلی و قدرت و استفاده از قطعات استاندارد و متناسب با دستگاه." }, { title: "تست نهایی", text: "تست عملکرد، شارژ و دشارژ باتری و تحویل همراه با گزارش اقدامات انجام‌شده." }] },
  sales: { title: "فروش تجهیزات برق اضطراری", description: "انتخاب صحیح ظرفیت و فناوری، پیش از خرید", image: "/images/static/airplanes_in_night.webp", intro: "فروش در کلینیک یو پی اس با نیازسنجی فنی شروع می‌شود. نوع بار، توان لحظه‌ای، زمان پشتیبانی، امکان توسعه و شرایط محیطی بررسی می‌شوند تا انتخاب نهایی اقتصادی و قابل اتکا باشد.", sections: [{ title: "یو پی اس و باتری", text: "راهکارهای آنلاین و لاین‌اینتراکتیو به همراه بانک باتری متناسب با زمان پشتیبانی مورد نیاز." }, { title: "استابیلایزر", text: "تثبیت ولتاژ و محافظت از تجهیزات در برابر نوسان‌های شبکه برق." }, { title: "موتور برق و دیزل ژنراتور", text: "تأمین برق پشتیبان برای بارهای متوسط و بزرگ به همراه تابلو و تجهیزات جانبی." }] },
};

export default function StaticLandingPage({ page }) {
  const data = pages[page];
  return <><PageHero title={data.title} description={data.description} image={data.image} /><LandingSection><Breadcrumbs items={page === "services" || page === "about" ? [{ label: data.title }] : [{ label: "خدمات", href: "/services" }, { label: data.title }]} /><p className="max-w-4xl text-lg leading-9 text-slate-300">{data.intro}</p><div className="mt-10 grid gap-6 md:grid-cols-3">{(data.cards || data.sections).map((section) => { const content = <div className="h-full rounded-2xl border border-white/10 bg-white/[0.04] p-6 transition hover:border-cyan-300/35"><h2 className="text-xl font-black text-white">{section.title}</h2><p className="mt-4 leading-8 text-slate-400">{section.text}</p>{section.href ? <span className="mt-5 inline-block text-sm font-bold text-cyan-300">مشاهده جزئیات ←</span> : null}</div>; return section.href ? <Link key={section.title} href={section.href}>{content}</Link> : <div key={section.title}>{content}</div>; })}</div>{page === "about" ? <div className="mt-12 overflow-hidden rounded-2xl"><img src="/images/brands/cooperating_brands.webp" alt="برندهای همکار" className="w-full" /></div> : null}</LandingSection></>;
}
