import NotificationsProvider from "@/hooks/useNotifications/NotificationsProvider";
import "./globals.css";
import DialogsProvider from "@/hooks/useDialogs/DialogsProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className="min-h-full flex flex-col">
        <NotificationsProvider>
          <DialogsProvider>{children}</DialogsProvider>
        </NotificationsProvider>
      </body>
    </html>
  );
}
